# Generated by Django 4.1.7 on 2023-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_data', models.JSONField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults_count', models.PositiveIntegerField(default=1)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('infants_count', models.PositiveIntegerField(default=0)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
