# Generated by Django 4.1.7 on 2023-03-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_cartitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
