# Generated by Django 4.1.7 on 2023-03-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_cartitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='searchedroute',
            name='adults_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchedroute',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchedroute',
            name='infants_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
