# Generated by Django 4.1.7 on 2023-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_cartitem_status_searchedroute_adults_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='flight_data',
            field=models.JSONField(null=True),
        ),
    ]
