# Generated by Django 4.1.7 on 2023-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_alter_cartitem_flight_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='flight_data',
            field=models.JSONField(default=dict),
        ),
    ]
