# Generated by Django 4.1.7 on 2023-03-04 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoWayFlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('travel_class', models.CharField(default='all', max_length=10)),
                ('non_stop', models.BooleanField(default=False)),
                ('return_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('infants', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('max_price', models.IntegerField()),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneWayFlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('travel_class', models.CharField(default='all', max_length=10)),
                ('non_stop', models.BooleanField(default=False)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('infants', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('max_price', models.IntegerField()),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
