# Generated by Django 4.1.7 on 2023-03-06 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_hotelsearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('passport_holder', models.BooleanField(default=False)),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry', models.DateField()),
                ('passport_country', models.CharField(max_length=50)),
                ('passport_validitycountry', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
