# Generated by Django 4.1.7 on 2023-03-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_traveler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('natianality', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='twowayflightsearch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='city',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='email',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='passport_holder',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='passport_validitycountry',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='phone',
        ),
        migrations.AddField(
            model_name='traveler',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='id_card_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='id_card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='id_card_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='passport_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='passport_expiry',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='OneWayFlightSearch',
        ),
        migrations.DeleteModel(
            name='TwoWayFlightSearch',
        ),
    ]
