# Generated by Django 4.1.7 on 2023-03-22 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_personal_info_remove_twowayflightsearch_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('vendorCode', models.CharField(max_length=50, null=True)),
                ('cardNumber', models.CharField(max_length=50, null=True)),
                ('cardHolderName', models.CharField(max_length=50, null=True)),
                ('expiryMonth', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='title',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='type',
        ),
        migrations.AddField(
            model_name='traveler',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveler',
            name='document_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_issuanceDATE',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
