# Generated by Django 4.1.7 on 2023-03-27 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_payment_remove_traveler_title_remove_traveler_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
