# Generated by Django 4.1.7 on 2023-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_personal_info_bio_personal_info_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_id', models.CharField(max_length=50, null=True)),
                ('traveler_message', models.CharField(max_length=50, null=True)),
                ('traveler_list', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
