# Generated by Django 4.1.7 on 2023-03-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_traveller_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveller_info',
            old_name='user',
            new_name='owner',
        ),
    ]
