# Generated by Django 4.1.7 on 2023-03-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('flight_data', models.TextField(max_length=6000)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
