# Generated by Django 4.1.7 on 2023-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttmp',
            name='flight_data',
            field=models.JSONField(max_length=8000),
        ),
    ]
