# Generated by Django 4.1.7 on 2023-03-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsv2', '0002_alter_flighttmp_flight_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttmp',
            name='flight_data',
            field=models.JSONField(),
        ),
    ]
