# Generated by Django 4.1.7 on 2023-03-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsv2', '0004_alter_flighttmp_flight_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttmp',
            name='flight_data',
        ),
        migrations.AddField(
            model_name='flighttmp',
            name='flight_data3',
            field=models.JSONField(null=True),
        ),
    ]
