# Generated by Django 4.1.7 on 2023-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsv2', '0005_remove_flighttmp_flight_data_flighttmp_flight_data3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flighttmp',
            name='flight_data3',
        ),
        migrations.AddField(
            model_name='flighttmp',
            name='flight_data',
            field=models.JSONField(null=True),
        ),
    ]
