# Generated by Django 4.1.7 on 2023-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightsv2', '0006_remove_flighttmp_flight_data3_flighttmp_flight_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttmp',
            name='flight_data',
            field=models.JSONField(default=dict),
        ),
    ]
